

SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, u.GENDER, COUNT(distinct o.USER_ID) AS USERS
    FROM ONLINE_SALE o
    JOIN USER_INFO u ON o.USER_ID=u.USER_ID
    WHERE u.GENDER IN (0,1)
    GROUP BY YEAR, MONTH, GENDER
    ORDER BY YEAR ,MONTH, GENDER