-- 코드를 입력하세요
SELECT HOUR(DATETIME) as HOUR, COUNT(ANIMAL_ID) as `COUNT`
FROM ANIMAL_OUTS
GROUP BY 1
ORDER BY 1;

WITH RECURSIVE TIME AS (
    
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
      FROM TIME 
     WHERE HOUR < 23
)

SELECT TIME.HOUR, COALESCE(a.`COUNT`,0)
FROM TIME
LEFT OUTER JOIN (SELECT HOUR(DATETIME) as HOUR, COUNT(ANIMAL_ID) as `COUNT`
FROM ANIMAL_OUTS
GROUP BY 1) a
ON TIME.HOUR = a.HOUR;