-- 코드를 입력하세요
SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, SUBSTRING(b.CREATED_DATE, 1,10) AS CREATED_DATE
FROM USED_GOODS_BOARD a
INNER JOIN USED_GOODS_REPLY b ON a.BOARD_ID = b.BOARD_ID
WHERE SUBSTRING(a.CREATED_DATE, 1, 7) = '2022-10'
ORDER BY 6 asc, 1 asc;